//! 3.0 — `Balanced` and `Minimal` convert exactly as they did in `2.9.0`.
//!
//! **What this replaces.** `2.4.2` added two properties here: **P1**, that an
//! option documented as inert is inert (flip any of the six no-effect fields,
//! byte-identical output in every mode), and **P2**, that `Balanced`, `Strict`,
//! `Semantic` and `Preserve` agree byte for byte. Both were about things `3.0`
//! removed -- the six fields and the three alias modes -- so both went with
//! them. Their job was to prove the removal would change nothing, and it did
//! that: before they were deleted, the `2.9.0` binary was run over this corpus
//! with `unwrap_unknown_wrappers` forced both ways in both modes, and every
//! output matched what `3.0` writes.
//!
//! **What survives, and why it has to.** After the removal nothing else asserts
//! that promise, and it is the one `3.0` makes: *nothing about how a document
//! converts changes*. So this asserts it directly, for the two surviving modes,
//! over the same corpus P1 and P2 ran over: every output must be byte-identical
//! to what the published `2.9.0` produced, which is stored under
//! `golden_2_9_0/<mode>/<corpus path>.md` (generated by running the `2.9.0`
//! binary, not by running this tree).
//!
//! **Changing a golden is a decision, not a fix.** A later release that
//! deliberately changes conversion output must change the affected goldens in
//! the same commit, and say why in the commit message -- the same discipline as
//! any protected bytes. A golden edited to make this pass without that reason
//! is the failure this file exists to prevent.
//!
//! The corpus is every `.html` file in the directories below (up to 50 kB), so
//! adding an input adds a case, not code -- and, for the golden to exist, a
//! golden file, which is what the missing-golden message says.

use std::path::{Path, PathBuf};

use mdka::options::{ConversionMode, ConversionOptions};

use crate::harness::mdka_convert;

const DIRS: &[&str] = &[
    "tests/output_validity/mode_corpus",
    "tests/output_validity/runner_fixtures",
    "tests/output_validity/corpus_proof",
    "benches/benchdata",
];

const MODES: [(ConversionMode, &str); 2] = [
    (ConversionMode::Balanced, "balanced"),
    (ConversionMode::Minimal, "minimal"),
];

const GOLDEN_ROOT: &str = "tests/output_validity/golden_2_9_0";

fn corpus() -> Vec<(String, String)> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut out = Vec::new();
    for dir in DIRS {
        let mut files: Vec<PathBuf> = std::fs::read_dir(root.join(dir))
            .unwrap_or_else(|e| panic!("{dir}: {e}"))
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().is_some_and(|x| x == "html"))
            .collect();
        files.sort();
        for p in files {
            // The larger benchmark files (deep_nest alone is quadratic in depth) cost half a minute in a debug
            // build. None of the excluded files (deep_nest, flat, large, medium, scale_50k, scale_500k,
            // scale_5m) contains a `<td>` or `<th>`, so they cannot express a cell-context defect; everything
            // smaller is here.
            if std::fs::metadata(&p).unwrap().len() > 50_000 {
                continue;
            }
            let html = std::fs::read_to_string(&p).unwrap();
            let name = format!("{dir}/{}", p.file_name().unwrap().to_string_lossy());
            out.push((name, html));
        }
    }
    assert!(
        out.len() >= 50,
        "corpus shrank to {} files; a property over an empty set proves nothing",
        out.len()
    );
    out
}

fn golden(mode_dir: &str, name: &str) -> String {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join(GOLDEN_ROOT)
        .join(mode_dir)
        .join(format!("{name}.md"));
    std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "no 2.9.0 golden for {name} [{mode_dir}] at {}: {e}. A new corpus file needs its golden \
             generated by running the *published 2.9.0* over it -- not by running this tree.",
            path.display()
        )
    })
}

fn show(s: &str) -> String {
    s.replace('\n', "⏎")
}

#[test]
fn p3_balanced_and_minimal_are_byte_identical_to_published_2_9_0() {
    let mut violations = Vec::new();
    let corpus = corpus();
    for (name, html) in &corpus {
        for (mode, dir) in MODES {
            let expected = golden(dir, name);
            let got = mdka_convert(html, &ConversionOptions::for_mode(mode));
            if got != expected {
                violations.push(format!(
                    "{name} [{mode}]:\n    2.9.0: {}\n    now:   {}",
                    show(&expected),
                    show(&got)
                ));
            }
        }
    }
    assert!(
        violations.is_empty(),
        "{} of {} (file, mode) outputs differ from published 2.9.0:\n{}",
        violations.len(),
        corpus.len() * MODES.len(),
        violations.join("\n")
    );
}

/// The comparison above can see a difference. If the two golden sets were
/// identical (or both empty) P3 would pass whatever the converter did, so
/// this asserts the modes really do differ on part of the corpus -- and that
/// feeding one mode's golden to the other mode's output is caught.
#[test]
fn p3_can_tell_the_two_modes_apart() {
    let corpus = corpus();
    let mut differing = 0;
    for (name, html) in &corpus {
        let balanced_golden = golden("balanced", name);
        let minimal_out = mdka_convert(html, &ConversionOptions::for_mode(ConversionMode::Minimal));
        if minimal_out != balanced_golden {
            differing += 1;
        }
    }
    assert!(
        differing >= 3,
        "only {differing} corpus files distinguish Minimal from Balanced; P3 could not notice \
         the two modes being swapped"
    );
}
