/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * What happened to one file in a bulk conversion.
 *
 * **Exactly one of `dest` and `error` is set**, and `ok` says which
 * (`ok === (dest !== undefined)`). TypeScript cannot express "exactly one of",
 * which is why `ok` exists: check it, and the other fields follow.
 *
 * A single-file conversion does not return one of these: it resolves to the
 * destination path, or rejects. Only a bulk call reports per file, because one
 * failure must not abort the others.
 */
export interface FileOutcome {
  /** The input path, as it was passed in. */
  src: string
  /** The output path that was written. Set when `ok` is true. */
  dest?: string
  /** Why this file failed. Set when `ok` is false. */
  error?: string
  /** Whether this file was converted. */
  ok: boolean
}

/**
 * Converts many HTML files into `outDir` and resolves to one `FileOutcome`
 * per input, in input order.
 *
 * **A failing file does not reject the promise:** its entry has `ok: false` and
 * `error` set, and the other files are converted regardless. The promise rejects
 * only when the call as a whole cannot proceed -- `outDir` cannot be created
 * (`cannot create out_dir: …`) or `options` is wrong. That is the design, not an
 * inconsistency with `htmlFileToMarkdown`: with one file, failing the call is the
 * answer; with many, one bad file must not hide the rest.
 */
export declare function htmlFilesToMarkdown(paths: Array<string>, outDir: string, options?: JsConversionOptions | undefined | null): Promise<Array<FileOutcome>>

/**
 * Converts one HTML file and resolves to the path that was written.
 *
 * When `outDir` is null or undefined, the `.md` file is written next to the input.
 * **A failure rejects the promise** with an `Error` whose message begins
 * `IO error: `; there is no result object to inspect, because the caller asked
 * about exactly one file. (`htmlFilesToMarkdown` differs on purpose: it reports
 * per file.)
 *
 * ```js
 * // writes into the same directory
 * const dest = await htmlFileToMarkdown('index.html')
 *
 * // writes into a different directory
 * const dest = await htmlFileToMarkdown('index.html', 'out/')
 * ```
 */
export declare function htmlFileToMarkdown(path: string, outDir?: string | undefined | null, options?: JsConversionOptions | undefined | null): Promise<string>

/**
 * Converts an HTML string to Markdown. Throws only if `options` is wrong: an
 * unknown or removed key, or an unknown mode. HTML itself cannot fail it.
 */
export declare function htmlToMarkdown(html: string, options?: JsConversionOptions | undefined | null): string

/**
 * Asynchronous form of `htmlToMarkdown`: the conversion runs on a worker
 * thread. Rejects (or throws, for a bad key) only if `options` is wrong.
 */
export declare function htmlToMarkdownAsync(html: string, options?: JsConversionOptions | undefined | null): Promise<string>

/**
 * Converts multiple HTML strings to Markdown, each independently. Cannot
 * fail on the HTML, so it returns plain strings, not a result type (RFC 039
 * §3 A2). Its options are optional the same way every other Node function's
 * now are: `htmlToMarkdown`, `htmlToMarkdownAsync`, `htmlFileToMarkdown` and
 * `htmlFilesToMarkdown` had a separate `…With` twin until 3.0. There is no async
 * twin -- the underlying Rust call is CPU-bound and already parallel across
 * cores internally (via rayon) when the `parallel` feature is on, so a
 * `spawn_blocking` wrapper here would add a thread hop without shortening the
 * work.
 */
export declare function htmlToMarkdownMany(htmls: Array<string>, options?: JsConversionOptions | undefined | null): Array<string>

/**
 * Options for a conversion. Every field is optional. An **unrecognised key is
 * an error** (see [`StrictOptions`]), so a typo -- or an option that was removed in
 * 3.0 -- fails loudly instead of being ignored.
 */
export interface JsConversionOptions {
  /** "balanced" | "minimal" */
  mode?: string
  preserveIds?: boolean
  dropInteractiveShell?: boolean
}

export declare function version(): string
