/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Result of a file conversion. */
export interface ConvertResult {
  /** Path of the input file that was converted. */
  src: string
  /** Path of the output file that was written. */
  dest?: string
  /** Error message when the conversion failed (bulk conversion only). */
  error?: string
}

export declare function htmlFilesToMarkdown(paths: Array<string>, outDir: string): Promise<Array<ConvertResult>>

export declare function htmlFilesToMarkdownWith(paths: Array<string>, outDir: string, options?: JsConversionOptions | undefined | null): Promise<Array<ConvertResult>>

/**
 * Converts a single HTML file (default mode).
 *
 * When `outDir` is null or undefined, the `.md` file is written next to the input.
 *
 * ```js
 * // writes into the same directory
 * const r = await htmlFileToMarkdown('index.html')
 * console.log(r.src, '->', r.dest)
 *
 * // writes into a different directory
 * const r = await htmlFileToMarkdown('index.html', 'out/')
 * ```
 */
export declare function htmlFileToMarkdown(path: string, outDir?: string | undefined | null): Promise<ConvertResult>

/** Converts a single HTML file with the given options. */
export declare function htmlFileToMarkdownWith(path: string, outDir?: string | undefined | null, options?: JsConversionOptions | undefined | null): Promise<ConvertResult>

export declare function htmlToMarkdown(html: string): string

export declare function htmlToMarkdownAsync(html: string): Promise<string>

export declare function htmlToMarkdownWith(html: string, options?: JsConversionOptions | undefined | null): string

export declare function htmlToMarkdownWithAsync(html: string, options?: JsConversionOptions | undefined | null): Promise<string>

export interface JsConversionOptions {
  /** "balanced" | "strict" | "minimal" | "semantic" | "preserve" */
  mode?: string
  preserveIds?: boolean
  preserveClasses?: boolean
  preserveDataAttrs?: boolean
  preserveAriaAttrs?: boolean
  dropInteractiveShell?: boolean
  unwrapUnknownWrappers?: boolean
}

export declare function version(): string
