'use strict'

// RFC 040 Part B -- the package entry point (`main` in package.json).
//
// `index.js` is generated by `napi build` and is regenerated on every build, so
// it cannot be edited: a patch there is reverted with nothing to warn anyone.
// Its load-failure message blames an npm bug and prescribes a reinstall. On a
// platform we publish no binary for there is no npm bug and the reinstall can
// never succeed, and the message contradicts our installation page, which
// describes that situation accurately. This file owns the message instead.
//
// It changes nothing on success: the module it exports is `index.js`'s own,
// every export included, with no list to keep in step.

// Every platform a native package is published for. Kept in step with the
// `napiplatform` values of .github/workflows/release-npm.yaml and with
// `napi.targets` in package.json by a test in test.js, so a target added in one
// place and not the others fails CI instead of shipping a false message.
const PUBLISHED = [
  'linux-x64-gnu',
  'linux-x64-musl',
  'linux-arm64-gnu',
  'linux-arm64-musl',
  'darwin-arm64',
  'win32-x64-msvc',
]

const INSTALLATION_PAGE = 'https://nabbisen.github.io/mdka-rs/getting-started/installation.html'

// glibc or musl on Linux, null elsewhere, 'unknown' if it cannot be told.
// Only runs on the failure path, so the cost of a diagnostic report is fine.
function detectLibc() {
  if (process.platform !== 'linux') return null
  const report = process.report
  if (!report || typeof report.getReport !== 'function') return 'unknown'
  const excludeNetwork = report.excludeNetwork
  try {
    report.excludeNetwork = true
    const r = report.getReport()
    if (r.header && r.header.glibcVersionRuntime) return 'glibc'
    if (Array.isArray(r.sharedObjects) && r.sharedObjects.some((f) => f.includes('libc.musl-') || f.includes('ld-musl-'))) {
      return 'musl'
    }
    return 'unknown'
  } catch {
    return 'unknown'
  } finally {
    report.excludeNetwork = excludeNetwork
  }
}

// The napi platform name for this process, e.g. `linux-x64-musl`.
function platformName(libc) {
  const { platform, arch } = process
  if (platform === 'linux') {
    const abi = libc === 'musl' ? 'musl' : libc === 'glibc' ? 'gnu' : 'unknown'
    // napi's own names for 32-bit ARM carry the float ABI: linux-arm-gnueabihf.
    return `${platform}-${arch}-${arch === 'arm' ? `${abi}eabihf` : abi}`
  }
  if (platform === 'win32') return `${platform}-${arch}-msvc`
  return `${platform}-${arch}`
}

function firstLine(error) {
  const message = error && error.message ? String(error.message) : String(error)
  return message.split('\n')[0]
}

// What `index.js` throws is `Error('Cannot find native binding. npm has a bug…')`,
// a fixed napi string that carries no information and, on a platform nothing
// was published for, is false. Its `cause` is the last of the real per-path
// failures, each chained to the one before. That chain is what is worth keeping
// and quoting. `index.js` has one other throw, `Error('Failed to load native
// binding')`, with no cause at all; there the error itself is all there is.
function underlying(thrown) {
  return thrown && thrown.cause ? thrown.cause : thrown
}

function describe(thrown) {
  return firstLine(underlying(thrown))
}

function diagnose(cause) {
  const libc = detectLibc()
  const name = platformName(libc)
  const facts =
    `process.platform=${process.platform}, process.arch=${process.arch}` +
    (libc ? `, libc=${libc}` : '') +
    `, node=${process.version}`
  const published = PUBLISHED.map((p) => `  ${p}`).join('\n')

  let message
  let code
  if (PUBLISHED.includes(name)) {
    code = 'MDKA_BINARY_LOAD_FAILED'
    message =
      `mdka could not load its native binary on ${name}. A prebuilt binary is published for this platform, ` +
      `so the platform is supported and something else stopped it from loading.\n\n` +
      `Underlying error: ${describe(cause)}\n\n` +
      `If that error is "Cannot find module '@mdka/lib-${name}'", the platform package was not installed next to ` +
      `mdka, which happens when node_modules was installed on a different platform from the one it runs on. ` +
      `Any other error is the operating system refusing the binary (for example a glibc older than it needs).\n\n` +
      `Details: ${facts}. The full chain of load errors is attached as error.cause.\n` +
      `${INSTALLATION_PAGE}`
  } else {
    code = 'MDKA_UNSUPPORTED_PLATFORM'
    message =
      `mdka has no prebuilt binary for this platform: ${name}. ` +
      `Installing succeeds on any platform, because the native binaries are optional dependencies, ` +
      `which is why this is only reported when mdka is first required.\n\n` +
      `Platforms with a published binary:\n${published}\n\n` +
      `mdka ships prebuilt binaries only, so it cannot be built from an installed copy. What can be done ` +
      `on an unsupported platform is described here:\n${INSTALLATION_PAGE}\n\n` +
      `Details: ${facts}. The underlying load error is attached as error.cause.`
  }

  const error = new Error(message, { cause: underlying(cause) })
  error.code = code
  return error
}

// Load once here so a failure is reported in our words. `index.js` stays in the
// require cache, so the export below is the same object, not a second load; it
// is written as a plain re-export so that Node's ESM loader can still see the
// named exports and `import { htmlToMarkdown } from 'mdka'` keeps working.
try {
  require('./index.js')
} catch (cause) {
  throw diagnose(cause)
}

module.exports = require('./index.js')
