[build-system]
requires      = ["maturin>=1.0"]
build-backend = "maturin"

[project]
name            = "mdka"
version = "2.6.0"
description     = "A HTML to Markdown converter that balances conversion quality with runtime efficiency written in Rust"
readme          = "README.md"
license         = "Apache-2.0"
requires-python = ">=3.10"
keywords        = ["html", "markdown", "converter"]
classifiers     = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "License :: OSI Approved :: Apache Software License",
]

[project.urls]
Homepage      = "https://nabbisen.github.io/mdka-rs/"
Documentation = "https://nabbisen.github.io/mdka-rs/getting-started/usage-python"
Source        = "https://github.com/nabbisen/mdka-rs"
Changelog     = "https://github.com/nabbisen/mdka-rs/blob/main/CHANGELOG.md"

[tool.maturin]
# Rust で生成されるネイティブモジュール名
module-name  = "mdka.mdka_python"
# Python パッケージのソースディレクトリ
python-source = "."
manifest-path = "Cargo.toml"
python-packages = ["mdka"]
