[book]
title       = "mdka — HTML to Markdown converter"
authors     = ["nabbisen<nabbisen@scqr.net>"]
description = "mdka: A HTML to Markdown converter that balances conversion quality with runtime efficiency"

language    = "en"

src         = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url  = "https://github.com/nabbisen/mdka-rs"
edit-url-template   = "https://github.com/nabbisen/mdka-rs/edit/main/docs/{path}"

no-section-label    = false

additional-css      = []

[output.html.search]
enable        = true
limit-results = 20
